apiVersion: v1
kind: Secret
metadata:
  name: tripmate-secrets
  namespace: tripmate
type: Opaque
stringData:
  JWT_SECRET: "c2VjdXJlLWV4YW0tc2VjcmV0LWtleS1taW4tMzItY2hhcnMtbG9uZyE="
  COOKIE_SECRET: "Y29va2llLXNlY3JldC1leGFtcGxlLW1pbi0zMi1jaGFycy1sb25nIQ=="
